-- data.sql for api-produtos
-- This script inserts initial data into the 'produtos' table.
-- NOTE: Manually setting data_criacao and data_atualizacao overrides
--       Hibernate's @CreationTimestamp and @UpdateTimestamp for these specific inserts.
--       This is generally NOT the recommended approach when using those annotations.
--       The 'id' column is auto-generated by the database (IDENTITY strategy).

INSERT INTO produtos (
    descricao, preco, categoria, quantidade_estoque, sku, marca, image_url, status, data_criacao, data_atualizacao
) VALUES (
    'Laptop Gamer Nitro 15"', 5500.00, 'ELETRONICOS', 25, 'ELET-LAP-NIT15', 'GamerTech', 'http://example.com/images/laptop_nitro.jpg', 'ATIVO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
);

INSERT INTO produtos (
    descricao, preco, categoria, quantidade_estoque, sku, marca, image_url, status, data_criacao, data_atualizacao
) VALUES (
    'Jaqueta Corta-Vento Impermeável', 189.90, 'ROUPAS', 150, 'ROUP-JAQ-IMP', 'AventuraWear', 'http://example.com/images/jaqueta_corta_vento.jpg', 'ATIVO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
);

INSERT INTO produtos (
    descricao, preco, categoria, quantidade_estoque, sku, marca, image_url, status, data_criacao, data_atualizacao
) VALUES (
    'Bota de Couro Adventure', 420.50, 'CALCADOS', 80, 'CALC-BOTA-ADV', 'TrilhaSegura', 'http://example.com/images/bota_adventure.jpg', 'ATIVO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
);

INSERT INTO produtos (
    descricao, preco, categoria, quantidade_estoque, sku, marca, image_url, status, data_criacao, data_atualizacao
) VALUES (
    'Kit Jardinagem Essencial 10 Peas', 99.99, 'CASA_E_JARDIM', 120, 'CASA-KIT-JARD10', 'VerdeVida', 'http://example.com/images/kit_jardinagem.jpg', 'ATIVO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
);

INSERT INTO produtos (
    descricao, preco, categoria, quantidade_estoque, sku, marca, image_url, status, data_criacao, data_atualizacao
) VALUES (
    'Livro "O Cdigo Perdido"', 45.00, 'LIVROS', 300, 'LIVR-COD-PERD', 'Editora Mistério', 'http://example.com/images/livro_codigo.jpg', 'ATIVO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
);

INSERT INTO produtos (
    descricao, preco, categoria, quantidade_estoque, sku, marca, image_url, status, data_criacao, data_atualizacao
) VALUES (
    'Jogo de Tabuleiro Estratégia Medieval', 250.00, 'BRINQUEDOS_E_JOGOS', 50, 'BRINQ-JOGO-MED', 'ReinoLudico', 'http://example.com/images/jogo_medieval.jpg', 'ATIVO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
);

INSERT INTO produtos (
    descricao, preco, categoria, quantidade_estoque, sku, marca, image_url, status, data_criacao, data_atualizacao
) VALUES (
    'Bicicleta Mountain Bike Aro 29', 1800.00, 'ESPORTES_E_LAZER', 35, 'ESP-BIKE-MTB29', 'PedalRadical', 'http://example.com/images/bike_mtb.jpg', 'ATIVO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
);

INSERT INTO produtos (
    descricao, preco, categoria, quantidade_estoque, sku, marca, image_url, status, data_criacao, data_atualizacao
) VALUES (
    'Creme Hidratante Facial Noturno', 75.80, 'BELEZA_E_CUIDADO_PESSOAL', 200, 'BELE-CREME-NOT', 'PeleRadiante', 'http://example.com/images/creme_noturno.jpg', 'ATIVO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
);

INSERT INTO produtos (
    descricao, preco, categoria, quantidade_estoque, sku, marca, image_url, status, data_criacao, data_atualizacao
) VALUES (
    'Pneu Aro 15 Performance', 350.00, 'AUTOMOTIVO', 90, 'AUTO-PNEU-15P', 'RodaForte', 'http://example.com/images/pneu_aro15.jpg', 'ATIVO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
);

INSERT INTO produtos (
    descricao, preco, categoria, quantidade_estoque, sku, marca, image_url, status, data_criacao, data_atualizacao
) VALUES (
    'Monitor LED 24" Full HD', 899.90, 'ELETRONICOS', 60, 'ELET-MON-24FHD', 'VisioMax', 'http://example.com/images/monitor_24.jpg', 'ATIVO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
);

-- Example of an inactive product
INSERT INTO produtos (
    descricao, preco, categoria, quantidade_estoque, sku, marca, image_url, status, data_criacao, data_atualizacao
) VALUES (
    'Modelo Antigo Smartphone Y', 800.00, 'ELETRONICOS', 0, 'ELET-SMART-YOLD', 'TechCorp', 'http://example.com/images/smarty_old.jpg', 'INATIVO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
);

-- Example of an out-of-stock product
INSERT INTO produtos (
    descricao, preco, categoria, quantidade_estoque, sku, marca, image_url, status, data_criacao, data_atualizacao
) VALUES (
    'Camisa Polo Edição Limitada', 120.00, 'ROUPAS', 0, 'ROUP-POLO-LTD', 'VestBem', 'http://example.com/images/polo_ltd.jpg', 'ESGOTADO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
);