package br.com.produto.api_produtos.dto;

import br.com.produto.api_produtos.entity.ProdutoEntity;
import br.com.produto.api_produtos.enums.Categoria;
import lombok.*;

@Getter
@Setter
@Builder // Lombok annotation to provide the builder pattern
@AllArgsConstructor // Lombok annotation for constructor with all args (used by builder)
@NoArgsConstructor // Lombok annotation for no-args constructor
public class ProdutoDTO {
    private String descricao;
    private Double preco;
    private Categoria categoria;

    /**
     * Creates a ProdutoDTO instance from a ProdutoEntity instance.
     *
     * @param produtoEntity The entity to map from.
     * @return A new ProdutoDTO instance populated with data from the entity,
     *         or null if the input entity is null.
     */
    public static ProdutoDTO from(ProdutoEntity produtoEntity) {
        // Optional: Handle null input gracefully
        if (produtoEntity == null) {
            return null;
        }

        // Use the builder pattern provided by Lombok's @Builder
        return ProdutoDTO.builder()
                .descricao(produtoEntity.getDescricao()) // Map descricao
                .preco(produtoEntity.getPreco())         // Map preco
                .categoria(produtoEntity.getCategoria()) // Map categoria
                .build();                                // Build the DTO instance
    }

    // Optional: Add a method to convert DTO back to Entity (useful for saving/updating)
    public ProdutoEntity toEntity() {
        ProdutoEntity entity = new ProdutoEntity();
        entity.setDescricao(this.descricao);
        entity.setPreco(this.preco);
        entity.setCategoria(this.categoria);
        // Note: The ID is not set here as it's typically generated by the database
        // or assigned when updating an existing entity.
        return entity;
    }
}