package br.com.produto.api_produtos.entity;

import br.com.produto.api_produtos.enums.Categoria;
import jakarta.persistence.*; // Using jakarta persistence for Spring Boot 3+
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Entity // Marks this class as a JPA entity
@Table(name = "produtos") // Specifies the table name in the database
@Getter // Lombok annotation to generate getters
@Setter // Lombok annotation to generate setters
@NoArgsConstructor // Lombok annotation to generate a no-argument constructor (required by JPA)
public class ProdutoEntity {

    @Id // Marks this field as the primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    // Specifies the generation strategy for the primary key.
    // GenerationType.IDENTITY is suitable for H2, MySQL, PostgreSQL, etc.,
    // relying on the database's auto-increment feature.
    private Long id;

    @Column(name = "descricao", nullable = false, length = 255) // Maps to the 'descricao' column, cannot be null
    private String descricao;

    @Column(name = "preco") // Maps to the 'preco' column
    private Double preco;

    @Enumerated(EnumType.STRING) // Specifies that the enum should be stored as a String in the DB
    @Column(name = "categoria", nullable = false) // Maps to the 'categoria' column, cannot be null
    private Categoria categoria;

    // Optional: Constructor without ID (useful for creating new entities before saving)
    public ProdutoEntity(String descricao, Double preco, Categoria categoria) {
        this.descricao = descricao;
        this.preco = preco;
        this.categoria = categoria;
    }

    // Getters, Setters, and NoArgsConstructor are generated by Lombok annotations.
    // equals() and hashCode() might be useful to implement as well, especially
    // if you work with entities in Sets or compare them frequently.
}